# Generated by Django 3.1.3 on 2020-12-04 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20201202_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
