# Generated by Django 3.1.3 on 2020-12-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201202_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reference',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='smptserver',
            field=models.CharField(max_length=100),
        ),
    ]
