# Generated by Django 3.1.3 on 2020-12-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0002_auto_20201207_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_img'),
        ),
    ]
